#!/usr/bin/env ruby

require "mustache"

index = Mustache.new
updated_at = Time.now.strftime "%c"
message = ARGV.join ' '

index.template = File.read File.expand_path("./index.html.mustache")
html = index.render :updated_at => updated_at, :message => message

File.write File.expand_path("./index.html"), html

`git add index.html`
`git commit -m"#{message}"`
`git push`
